##
## This is the Rust/Elm image for CI.
## This image is based on the Rust/Node image.
## Use this image for combined Rust and Elm projects.
##

FROM vibbioinfocore/rust-node-ci:latest

# Install elm, elm-format, elm-test, etc
RUN npm install -g elm elm-format elm-test elm-verify-examples
